# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\rlpazdnikov\Desktop\Cannibal rabbit\Preparation_Import\prepare.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 298)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 298))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 298))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/resor/preparation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.ConvertToCSV = QtWidgets.QPushButton(self.centralwidget)
        self.ConvertToCSV.setEnabled(False)
        self.ConvertToCSV.setGeometry(QtCore.QRect(0, 52, 262, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConvertToCSV.setFont(font)
        self.ConvertToCSV.setObjectName("ConvertToCSV")
        self.OpenCatalog = QtWidgets.QPushButton(self.centralwidget)
        self.OpenCatalog.setGeometry(QtCore.QRect(0, 101, 262, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OpenCatalog.setFont(font)
        self.OpenCatalog.setObjectName("OpenCatalog")
        self.putFilestoFTP = QtWidgets.QPushButton(self.centralwidget)
        self.putFilestoFTP.setEnabled(False)
        self.putFilestoFTP.setGeometry(QtCore.QRect(0, 150, 262, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.putFilestoFTP.setFont(font)
        self.putFilestoFTP.setObjectName("putFilestoFTP")
        self.sendMailtoSup = QtWidgets.QPushButton(self.centralwidget)
        self.sendMailtoSup.setEnabled(False)
        self.sendMailtoSup.setGeometry(QtCore.QRect(0, 248, 262, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendMailtoSup.setFont(font)
        self.sendMailtoSup.setObjectName("sendMailtoSup")
        self.clearDirectory = QtWidgets.QPushButton(self.centralwidget)
        self.clearDirectory.setEnabled(True)
        self.clearDirectory.setGeometry(QtCore.QRect(0, 199, 262, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearDirectory.setFont(font)
        self.clearDirectory.setObjectName("clearDirectory")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(2, 29, 186, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, 4, 261, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.saveFTPDirName = QtWidgets.QPushButton(self.centralwidget)
        self.saveFTPDirName.setGeometry(QtCore.QRect(187, 28, 74, 22))
        self.saveFTPDirName.setObjectName("saveFTPDirName")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(261, 1, 740, 298))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.JustColorDNTTCH = QtWidgets.QGroupBox(self.centralwidget)
        self.JustColorDNTTCH.setEnabled(False)
        self.JustColorDNTTCH.setGeometry(QtCore.QRect(0, 0, 1001, 301))
        self.JustColorDNTTCH.setStyleSheet("background-color: rgb(0, 120, 215);")
        self.JustColorDNTTCH.setTitle("")
        self.JustColorDNTTCH.setObjectName("JustColorDNTTCH")
        self.JustColorDNTTCH.raise_()
        self.ConvertToCSV.raise_()
        self.OpenCatalog.raise_()
        self.putFilestoFTP.raise_()
        self.sendMailtoSup.raise_()
        self.clearDirectory.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.saveFTPDirName.raise_()
        self.textBrowser.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preparation import v0.1 by Doctor_Cid"))
        self.ConvertToCSV.setText(_translate("MainWindow", "Конвертировать файл в CSV"))
        self.OpenCatalog.setText(_translate("MainWindow", "Открыть папки с фото и файлом\n"
"ассортиментики"))
        self.putFilestoFTP.setText(_translate("MainWindow", "Отправить файлы на ФТП"))
        self.sendMailtoSup.setText(_translate("MainWindow", "Отправить письмо о запуске в Саппорт"))
        self.clearDirectory.setText(_translate("MainWindow", "Очистить папки"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Наименование папки на ФТП</span></p></body></html>"))
        self.saveFTPDirName.setText(_translate("MainWindow", "Сохранить"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
#import P_Ires


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
